version: '3.7'
services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            MONGO_INITDB_DATABASE: nettu-meeting
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_nettumeet_container:/data/db
        logging:
            driver: none
        container_name: nettu_mongodb
        
    redis:
        image: redis
        ports:
            - 6379:6379
        logging:
            driver: none
        container_name: nettu_redis

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
        environment: 
            - discovery.type=single-node
        container_name: nettu_elasticsearch
        ports: ['9200:9200']
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.1.0
        container_name: nettu_kibana
        ports: ['5601:5601']
        depends_on: ['elasticsearch']

    nettumeet:
        image: wbsu2003/nettu-meet:v1
        environment:
            NETTU_REDIS_HOST: 192.168.0.114
            NETTU_REDIS_PORT: 6379
            MONGODB_CONNECTION_STRING: mongodb://root:rootpassword@192.168.0.114:27017
            MONGODB_NAME: nettu-meeting
            NETTU_ELASTIC_URL: http://192.168.0.114:9200
            FRONTEND_URL: http://meet.xxsu.ml:8443
        container_name: nettu_meet
        ports: 
            - 5310:80
        depends_on: ['redis'] 

volumes:
    mongodb_data_nettumeet_container: 