version: "3.4"

services:
  app:
    image: monica:fpm
    environment:
      - DB_HOST=<host IP:port>
      - DB_USERNAME=monica
      - DB_PASSWORD=<your db passwor>
    volumes:
      - data:/var/www/html/storage
    restart: always

  web:
    build: ./web
    ports:
      - 3780:80
    depends_on:
      - app
    volumes:
      - data:/var/www/html/storage:ro
    restart: always

volumes:
  data:
    name: data
